// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: db_user.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DB_UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" bson:"_id"`
	PhonOrEmail string   `protobuf:"bytes,2,opt,name=PhonOrEmail,proto3" json:"PhonOrEmail,omitempty"`
	Password    string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	NickName    string   `protobuf:"bytes,4,opt,name=NickName,proto3" json:"NickName,omitempty"`
	HeadUrl     string   `protobuf:"bytes,5,opt,name=HeadUrl,proto3" json:"HeadUrl,omitempty"`
	UserRole    UserRole `protobuf:"varint,6,opt,name=UserRole,proto3,enum=UserRole" json:"UserRole,omitempty"`
	Token       string   `protobuf:"bytes,7,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *DB_UserData) Reset() {
	*x = DB_UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DB_UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB_UserData) ProtoMessage() {}

func (x *DB_UserData) ProtoReflect() protoreflect.Message {
	mi := &file_db_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB_UserData.ProtoReflect.Descriptor instead.
func (*DB_UserData) Descriptor() ([]byte, []int) {
	return file_db_user_proto_rawDescGZIP(), []int{0}
}

func (x *DB_UserData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DB_UserData) GetPhonOrEmail() string {
	if x != nil {
		return x.PhonOrEmail
	}
	return ""
}

func (x *DB_UserData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DB_UserData) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *DB_UserData) GetHeadUrl() string {
	if x != nil {
		return x.HeadUrl
	}
	return ""
}

func (x *DB_UserData) GetUserRole() UserRole {
	if x != nil {
		return x.UserRole
	}
	return UserRole_Guester
}

func (x *DB_UserData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//用户缓存
type Cache_UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db_UserData *DB_UserData `protobuf:"bytes,1,opt,name=Db_UserData,json=DbUserData,proto3" json:"Db_UserData,omitempty"` //用户信息
	IsOnLine    bool         `protobuf:"varint,2,opt,name=IsOnLine,proto3" json:"IsOnLine,omitempty"`                      //是否在线
}

func (x *Cache_UserData) Reset() {
	*x = Cache_UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cache_UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache_UserData) ProtoMessage() {}

func (x *Cache_UserData) ProtoReflect() protoreflect.Message {
	mi := &file_db_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache_UserData.ProtoReflect.Descriptor instead.
func (*Cache_UserData) Descriptor() ([]byte, []int) {
	return file_db_user_proto_rawDescGZIP(), []int{1}
}

func (x *Cache_UserData) GetDb_UserData() *DB_UserData {
	if x != nil {
		return x.Db_UserData
	}
	return nil
}

func (x *Cache_UserData) GetIsOnLine() bool {
	if x != nil {
		return x.IsOnLine
	}
	return false
}

var File_db_user_proto protoreflect.FileDescriptor

var file_db_user_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x0b,
	0x44, 0x42, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x68, 0x6f, 0x6e, 0x4f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x50, 0x68, 0x6f, 0x6e, 0x4f, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x65, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x25, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5b, 0x0a, 0x0e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d,
	0x0a, 0x0b, 0x44, 0x62, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x42, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x44, 0x62, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x73, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x49, 0x73, 0x4f, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_user_proto_rawDescOnce sync.Once
	file_db_user_proto_rawDescData = file_db_user_proto_rawDesc
)

func file_db_user_proto_rawDescGZIP() []byte {
	file_db_user_proto_rawDescOnce.Do(func() {
		file_db_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_user_proto_rawDescData)
	})
	return file_db_user_proto_rawDescData
}

var file_db_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_db_user_proto_goTypes = []interface{}{
	(*DB_UserData)(nil),    // 0: DB_UserData
	(*Cache_UserData)(nil), // 1: Cache_UserData
	(UserRole)(0),          // 2: UserRole
}
var file_db_user_proto_depIdxs = []int32{
	2, // 0: DB_UserData.UserRole:type_name -> UserRole
	0, // 1: Cache_UserData.Db_UserData:type_name -> DB_UserData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_db_user_proto_init() }
func file_db_user_proto_init() {
	if File_db_user_proto != nil {
		return
	}
	file_comm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_db_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DB_UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cache_UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_user_proto_goTypes,
		DependencyIndexes: file_db_user_proto_depIdxs,
		MessageInfos:      file_db_user_proto_msgTypes,
	}.Build()
	File_db_user_proto = out.File
	file_db_user_proto_rawDesc = nil
	file_db_user_proto_goTypes = nil
	file_db_user_proto_depIdxs = nil
}
